{% set name = "unifdef" %}
{% set version = "2.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://dotat.at/prog/unifdef/unifdef-{{ version }}.tar.xz
  sha256: 43ce0f02ecdcdc723b2475575563ddb192e988c886d368260bc0a63aee3ac400

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - make

test:
  commands:
    - unifdef -h  # [build_platform == target_platform]

about:
  home: https://dotat.at/prog/unifdef/
  summary: 'Selectively remove C preprocessor conditionals'
  description: |
    The unifdef utility selectively processes conditional C preprocessor #if
    and #ifdef directives. It removes from a file both the directives and the
    additional text that they delimit, while otherwise leaving the file
    alone.
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  doc_url: https://dotat.at/prog/unifdef/unifdef.txt
  dev_url: https://github.com/fanf2/unifdef

extra:
  recipe-maintainers:
    - matthiasdiener
